export const LANGUAGES = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', flag: '🇮🇹' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇵🇹' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺' },
  { code: 'zh', name: 'Chinese', nativeName: '中文', flag: '🇨🇳' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'ko', name: 'Korean', nativeName: '한국어', flag: '🇰🇷' },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe', flag: '🇹🇷' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands', flag: '🇳🇱' },
  { code: 'th', name: 'Thai', nativeName: 'ไทย', flag: '🇹🇭' },
  { code: 'el', name: 'Greek', nativeName: 'Ελληνικά', flag: '🇬🇷' },
];

// UI translations for the guest app
export const UI_TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    welcome: 'Welcome',
    selectLanguage: 'Select your language',
    roomService: 'Room Service',
    drinks: 'Drinks & Beverages',
    customRequest: 'Custom Request',
    invoice: 'My Invoice',
    towels: 'Towels',
    helpOpeningRoom: 'Help opening room',
    cleaning: 'Cleaning',
    bathroomService: 'Bathroom service',
    doNotDisturb: 'Do Not Disturb',
    sendRequest: 'Send Request',
    requestSent: 'Request sent!',
    requestSentDesc: 'Our team has been notified and will assist you shortly.',
    writeYourRequest: 'Write your request here...',
    back: 'Back',
    sending: 'Sending...',
    room: 'Room',
    thankYou: 'Thank you!',
    feedback: 'Feedback',
    overallRating: 'Overall Experience',
    serviceRating: 'Service Quality',
    cleanlinessRating: 'Cleanliness',
    foodRating: 'Food & Beverages',
    feedbackComment: 'Additional Comments',
    feedbackPlaceholder: 'Tell us about your experience...',
    submitFeedback: 'Submit Feedback',
    ratingRequired: 'Please rate your overall experience',
    feedbackSent: 'Feedback submitted!',
    feedbackSentDesc: 'Thank you for your feedback. We appreciate your input!',
  },
  ar: {
    welcome: 'مرحباً',
    selectLanguage: 'اختر لغتك',
    roomService: 'خدمة الغرف',
    drinks: 'المشروبات',
    customRequest: 'طلب خاص',
    invoice: 'فاتورتي',
    towels: 'مناشف',
    helpOpeningRoom: 'مساعدة في فتح الغرفة',
    cleaning: 'تنظيف',
    bathroomService: 'خدمة الحمام',
    doNotDisturb: 'عدم الإزعاج',
    sendRequest: 'إرسال الطلب',
    requestSent: 'تم إرسال الطلب!',
    requestSentDesc: 'تم إخطار فريقنا وسيساعدك قريباً.',
    writeYourRequest: 'اكتب طلبك هنا...',
    back: 'رجوع',
    sending: 'جاري الإرسال...',
    room: 'غرفة',
    thankYou: 'شكراً لك!',
    feedback: 'تقييم',
    overallRating: 'التجربة العامة',
    serviceRating: 'جودة الخدمة',
    cleanlinessRating: 'النظافة',
    foodRating: 'الطعام والمشروبات',
    feedbackComment: 'تعليقات إضافية',
    feedbackPlaceholder: 'أخبرنا عن تجربتك...',
    submitFeedback: 'إرسال التقييم',
    ratingRequired: 'يرجى تقييم تجربتك العامة',
    feedbackSent: 'تم إرسال التقييم!',
    feedbackSentDesc: 'شكراً لتقييمك. نقدر ملاحظاتك!',
  },
  fr: {
    welcome: 'Bienvenue',
    selectLanguage: 'Choisissez votre langue',
    roomService: 'Service en chambre',
    drinks: 'Boissons',
    customRequest: 'Demande personnalisée',
    invoice: 'Ma facture',
    towels: 'Serviettes',
    helpOpeningRoom: "Aide pour ouvrir la chambre",
    cleaning: 'Nettoyage',
    bathroomService: 'Service salle de bain',
    doNotDisturb: 'Ne pas déranger',
    sendRequest: 'Envoyer la demande',
    requestSent: 'Demande envoyée!',
    requestSentDesc: 'Notre équipe a été informée et vous assistera sous peu.',
    writeYourRequest: 'Écrivez votre demande ici...',
    back: 'Retour',
    sending: 'Envoi...',
    room: 'Chambre',
    thankYou: 'Merci!',
    feedback: 'Avis',
    overallRating: 'Expérience globale',
    serviceRating: 'Qualité du service',
    cleanlinessRating: 'Propreté',
    foodRating: 'Nourriture et boissons',
    feedbackComment: 'Commentaires supplémentaires',
    feedbackPlaceholder: 'Parlez-nous de votre expérience...',
    submitFeedback: 'Envoyer l\'avis',
    ratingRequired: 'Veuillez évaluer votre expérience globale',
    feedbackSent: 'Avis envoyé!',
    feedbackSentDesc: 'Merci pour votre retour. Nous apprécions vos commentaires!',
  },
  de: {
    welcome: 'Willkommen',
    selectLanguage: 'Wählen Sie Ihre Sprache',
    roomService: 'Zimmerservice',
    drinks: 'Getränke',
    customRequest: 'Individuelle Anfrage',
    invoice: 'Meine Rechnung',
    towels: 'Handtücher',
    helpOpeningRoom: 'Hilfe beim Öffnen des Zimmers',
    cleaning: 'Reinigung',
    bathroomService: 'Badezimmerservice',
    doNotDisturb: 'Bitte nicht stören',
    sendRequest: 'Anfrage senden',
    requestSent: 'Anfrage gesendet!',
    requestSentDesc: 'Unser Team wurde benachrichtigt und wird Ihnen in Kürze helfen.',
    writeYourRequest: 'Schreiben Sie Ihre Anfrage hier...',
    back: 'Zurück',
    sending: 'Wird gesendet...',
    room: 'Zimmer',
    thankYou: 'Danke!',
    feedback: 'Bewertung',
    overallRating: 'Gesamterlebnis',
    serviceRating: 'Servicequalität',
    cleanlinessRating: 'Sauberkeit',
    foodRating: 'Essen und Getränke',
    feedbackComment: 'Zusätzliche Kommentare',
    feedbackPlaceholder: 'Erzählen Sie uns von Ihrer Erfahrung...',
    submitFeedback: 'Bewertung abgeben',
    ratingRequired: 'Bitte bewerten Sie Ihr Gesamterlebnis',
    feedbackSent: 'Bewertung gesendet!',
    feedbackSentDesc: 'Vielen Dank für Ihre Bewertung!',
  },
  es: {
    welcome: 'Bienvenido',
    selectLanguage: 'Seleccione su idioma',
    roomService: 'Servicio de habitación',
    drinks: 'Bebidas',
    customRequest: 'Solicitud personalizada',
    invoice: 'Mi factura',
    towels: 'Toallas',
    helpOpeningRoom: 'Ayuda para abrir la habitación',
    cleaning: 'Limpieza',
    bathroomService: 'Servicio de baño',
    doNotDisturb: 'No molestar',
    sendRequest: 'Enviar solicitud',
    requestSent: '¡Solicitud enviada!',
    requestSentDesc: 'Nuestro equipo ha sido notificado y le asistirá en breve.',
    writeYourRequest: 'Escriba su solicitud aquí...',
    back: 'Volver',
    sending: 'Enviando...',
    room: 'Habitación',
    thankYou: '¡Gracias!',
  },
};

export function t(lang: string, key: string): string {
  return UI_TRANSLATIONS[lang]?.[key] || UI_TRANSLATIONS['en']?.[key] || key;
}
