export const LANGUAGES = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', flag: '🇮🇹' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇵🇹' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺' },
  { code: 'zh', name: 'Chinese', nativeName: '中文', flag: '🇨🇳' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'ko', name: 'Korean', nativeName: '한국어', flag: '🇰🇷' },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe', flag: '🇹🇷' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands', flag: '🇳🇱' },
  { code: 'th', name: 'Thai', nativeName: 'ไทย', flag: '🇹🇭' },
  { code: 'el', name: 'Greek', nativeName: 'Ελληνικά', flag: '🇬🇷' },
  { code: 'pl', name: 'Polish', nativeName: 'Polski', flag: '🇵🇱' },
];

const baseKeys = [
  'welcome', 'selectLanguage', 'roomService', 'drinks', 'customRequest', 'invoice',
  'towels', 'helpOpeningRoom', 'cleaning', 'bathroomService', 'doNotDisturb',
  'sendRequest', 'requestSent', 'requestSentDesc', 'writeYourRequest', 'back',
  'sending', 'room', 'thankYou', 'feedback', 'overallRating', 'serviceRating',
  'cleanlinessRating', 'foodRating', 'feedbackComment', 'feedbackPlaceholder',
  'submitFeedback', 'ratingRequired', 'feedbackSent', 'feedbackSentDesc',
  'hotDrinks', 'coldDrinks', 'juices', 'cocktails', 'beer', 'wine', 'spirits',
  'softDrinks', 'other', 'noDrinksAvailable', 'orderSummary', 'addToOrder',
  'total', 'invoiceItems',
];

// UI translations for the guest app
export const UI_TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    welcome: 'Welcome',
    selectLanguage: 'Select your language',
    roomService: 'Room Service',
    drinks: 'Drinks & Beverages',
    customRequest: 'Custom Request',
    invoice: 'My Invoice',
    towels: 'Towels',
    helpOpeningRoom: 'Help opening room',
    cleaning: 'Cleaning',
    bathroomService: 'Bathroom service',
    doNotDisturb: 'Do Not Disturb',
    sendRequest: 'Send Request',
    requestSent: 'Request sent!',
    requestSentDesc: 'Our team has been notified and will assist you shortly.',
    writeYourRequest: 'Write your request here...',
    back: 'Back',
    sending: 'Sending...',
    room: 'Room',
    thankYou: 'Thank you!',
    feedback: 'Feedback',
    overallRating: 'Overall Experience',
    serviceRating: 'Service Quality',
    cleanlinessRating: 'Cleanliness',
    foodRating: 'Food & Beverages',
    feedbackComment: 'Additional Comments',
    feedbackPlaceholder: 'Tell us about your experience...',
    submitFeedback: 'Submit Feedback',
    ratingRequired: 'Please rate your overall experience',
    feedbackSent: 'Feedback submitted!',
    feedbackSentDesc: 'Thank you for your feedback. We appreciate your input!',
    hotDrinks: 'Hot Drinks',
    coldDrinks: 'Cold Drinks',
    juices: 'Juices',
    cocktails: 'Cocktails',
    beer: 'Beer',
    wine: 'Wine',
    spirits: 'Spirits',
    softDrinks: 'Soft Drinks',
    other: 'Other',
    noDrinksAvailable: 'No drinks available at the moment.',
    orderSummary: 'Order Summary',
    addToOrder: 'Add to order',
    total: 'Total',
    invoiceItems: 'Items',
  },
  ar: {
    welcome: 'مرحباً',
    selectLanguage: 'اختر لغتك',
    roomService: 'خدمة الغرف',
    drinks: 'المشروبات',
    customRequest: 'طلب خاص',
    invoice: 'فاتورتي',
    towels: 'مناشف',
    helpOpeningRoom: 'مساعدة في فتح الغرفة',
    cleaning: 'تنظيف',
    bathroomService: 'خدمة الحمام',
    doNotDisturb: 'عدم الإزعاج',
    sendRequest: 'إرسال الطلب',
    requestSent: 'تم إرسال الطلب!',
    requestSentDesc: 'تم إخطار فريقنا وسيساعدك قريباً.',
    writeYourRequest: 'اكتب طلبك هنا...',
    back: 'رجوع',
    sending: 'جاري الإرسال...',
    room: 'غرفة',
    thankYou: 'شكراً لك!',
    feedback: 'تقييم',
    overallRating: 'التجربة العامة',
    serviceRating: 'جودة الخدمة',
    cleanlinessRating: 'النظافة',
    foodRating: 'الطعام والمشروبات',
    feedbackComment: 'تعليقات إضافية',
    feedbackPlaceholder: 'أخبرنا عن تجربتك...',
    submitFeedback: 'إرسال التقييم',
    ratingRequired: 'يرجى تقييم تجربتك العامة',
    feedbackSent: 'تم إرسال التقييم!',
    feedbackSentDesc: 'شكراً لتقييمك. نقدر ملاحظاتك!',
    hotDrinks: 'مشروبات ساخنة',
    coldDrinks: 'مشروبات باردة',
    juices: 'عصائر',
    cocktails: 'كوكتيلات',
    beer: 'بيرة',
    wine: 'نبيذ',
    spirits: 'مشروبات روحية',
    softDrinks: 'مشروبات غازية',
    other: 'أخرى',
    noDrinksAvailable: 'لا توجد مشروبات متاحة حالياً.',
    orderSummary: 'ملخص الطلب',
    addToOrder: 'أضف للطلب',
    total: 'الإجمالي',
    invoiceItems: 'العناصر',
  },
  fr: {
    welcome: 'Bienvenue',
    selectLanguage: 'Choisissez votre langue',
    roomService: 'Service en chambre',
    drinks: 'Boissons',
    customRequest: 'Demande personnalisée',
    invoice: 'Ma facture',
    towels: 'Serviettes',
    helpOpeningRoom: "Aide pour ouvrir la chambre",
    cleaning: 'Nettoyage',
    bathroomService: 'Service salle de bain',
    doNotDisturb: 'Ne pas déranger',
    sendRequest: 'Envoyer la demande',
    requestSent: 'Demande envoyée!',
    requestSentDesc: 'Notre équipe a été informée et vous assistera sous peu.',
    writeYourRequest: 'Écrivez votre demande ici...',
    back: 'Retour',
    sending: 'Envoi...',
    room: 'Chambre',
    thankYou: 'Merci!',
    feedback: 'Avis',
    overallRating: 'Expérience globale',
    serviceRating: 'Qualité du service',
    cleanlinessRating: 'Propreté',
    foodRating: 'Nourriture et boissons',
    feedbackComment: 'Commentaires supplémentaires',
    feedbackPlaceholder: 'Parlez-nous de votre expérience...',
    submitFeedback: 'Envoyer l\'avis',
    ratingRequired: 'Veuillez évaluer votre expérience globale',
    feedbackSent: 'Avis envoyé!',
    feedbackSentDesc: 'Merci pour votre retour. Nous apprécions vos commentaires!',
    hotDrinks: 'Boissons chaudes',
    coldDrinks: 'Boissons froides',
    juices: 'Jus',
    cocktails: 'Cocktails',
    beer: 'Bière',
    wine: 'Vin',
    spirits: 'Spiritueux',
    softDrinks: 'Boissons gazeuses',
    other: 'Autre',
    noDrinksAvailable: 'Aucune boisson disponible pour le moment.',
    orderSummary: 'Résumé de la commande',
    addToOrder: 'Ajouter à la commande',
    total: 'Total',
    invoiceItems: 'Articles',
  },
  de: {
    welcome: 'Willkommen',
    selectLanguage: 'Wählen Sie Ihre Sprache',
    roomService: 'Zimmerservice',
    drinks: 'Getränke',
    customRequest: 'Individuelle Anfrage',
    invoice: 'Meine Rechnung',
    towels: 'Handtücher',
    helpOpeningRoom: 'Hilfe beim Öffnen des Zimmers',
    cleaning: 'Reinigung',
    bathroomService: 'Badezimmerservice',
    doNotDisturb: 'Bitte nicht stören',
    sendRequest: 'Anfrage senden',
    requestSent: 'Anfrage gesendet!',
    requestSentDesc: 'Unser Team wurde benachrichtigt und wird Ihnen in Kürze helfen.',
    writeYourRequest: 'Schreiben Sie Ihre Anfrage hier...',
    back: 'Zurück',
    sending: 'Wird gesendet...',
    room: 'Zimmer',
    thankYou: 'Danke!',
    feedback: 'Bewertung',
    overallRating: 'Gesamterlebnis',
    serviceRating: 'Servicequalität',
    cleanlinessRating: 'Sauberkeit',
    foodRating: 'Essen und Getränke',
    feedbackComment: 'Zusätzliche Kommentare',
    feedbackPlaceholder: 'Erzählen Sie uns von Ihrer Erfahrung...',
    submitFeedback: 'Bewertung abgeben',
    ratingRequired: 'Bitte bewerten Sie Ihr Gesamterlebnis',
    feedbackSent: 'Bewertung gesendet!',
    feedbackSentDesc: 'Vielen Dank für Ihre Bewertung!',
    hotDrinks: 'Heißgetränke',
    coldDrinks: 'Kaltgetränke',
    juices: 'Säfte',
    cocktails: 'Cocktails',
    beer: 'Bier',
    wine: 'Wein',
    spirits: 'Spirituosen',
    softDrinks: 'Erfrischungsgetränke',
    other: 'Sonstiges',
    noDrinksAvailable: 'Derzeit keine Getränke verfügbar.',
    orderSummary: 'Bestellübersicht',
    addToOrder: 'Zur Bestellung hinzufügen',
    total: 'Gesamt',
    invoiceItems: 'Artikel',
  },
  es: {
    welcome: 'Bienvenido',
    selectLanguage: 'Seleccione su idioma',
    roomService: 'Servicio de habitación',
    drinks: 'Bebidas',
    customRequest: 'Solicitud personalizada',
    invoice: 'Mi factura',
    towels: 'Toallas',
    helpOpeningRoom: 'Ayuda para abrir la habitación',
    cleaning: 'Limpieza',
    bathroomService: 'Servicio de baño',
    doNotDisturb: 'No molestar',
    sendRequest: 'Enviar solicitud',
    requestSent: '¡Solicitud enviada!',
    requestSentDesc: 'Nuestro equipo ha sido notificado y le asistirá en breve.',
    writeYourRequest: 'Escriba su solicitud aquí...',
    back: 'Volver',
    sending: 'Enviando...',
    room: 'Habitación',
    thankYou: '¡Gracias!',
    feedback: 'Opinión',
    overallRating: 'Experiencia general',
    serviceRating: 'Calidad del servicio',
    cleanlinessRating: 'Limpieza',
    foodRating: 'Comida y bebidas',
    feedbackComment: 'Comentarios adicionales',
    feedbackPlaceholder: 'Cuéntenos sobre su experiencia...',
    submitFeedback: 'Enviar opinión',
    ratingRequired: 'Por favor califique su experiencia general',
    feedbackSent: '¡Opinión enviada!',
    feedbackSentDesc: '¡Gracias por sus comentarios!',
    hotDrinks: 'Bebidas calientes',
    coldDrinks: 'Bebidas frías',
    juices: 'Jugos',
    cocktails: 'Cócteles',
    beer: 'Cerveza',
    wine: 'Vino',
    spirits: 'Licores',
    softDrinks: 'Refrescos',
    other: 'Otro',
    noDrinksAvailable: 'No hay bebidas disponibles en este momento.',
    orderSummary: 'Resumen del pedido',
    addToOrder: 'Agregar al pedido',
    total: 'Total',
    invoiceItems: 'Artículos',
  },
  it: {
    welcome: 'Benvenuto',
    selectLanguage: 'Seleziona la tua lingua',
    roomService: 'Servizio in camera',
    drinks: 'Bevande',
    customRequest: 'Richiesta personalizzata',
    invoice: 'La mia fattura',
    towels: 'Asciugamani',
    helpOpeningRoom: 'Aiuto per aprire la stanza',
    cleaning: 'Pulizia',
    bathroomService: 'Servizio bagno',
    doNotDisturb: 'Non disturbare',
    sendRequest: 'Invia richiesta',
    requestSent: 'Richiesta inviata!',
    requestSentDesc: 'Il nostro team è stato avvisato e ti assisterà a breve.',
    writeYourRequest: 'Scrivi la tua richiesta qui...',
    back: 'Indietro',
    sending: 'Invio...',
    room: 'Camera',
    thankYou: 'Grazie!',
    feedback: 'Recensione',
    overallRating: 'Esperienza complessiva',
    serviceRating: 'Qualità del servizio',
    cleanlinessRating: 'Pulizia',
    foodRating: 'Cibo e bevande',
    feedbackComment: 'Commenti aggiuntivi',
    feedbackPlaceholder: 'Raccontaci la tua esperienza...',
    submitFeedback: 'Invia recensione',
    ratingRequired: 'Valuta la tua esperienza complessiva',
    feedbackSent: 'Recensione inviata!',
    feedbackSentDesc: 'Grazie per il tuo feedback!',
    hotDrinks: 'Bevande calde',
    coldDrinks: 'Bevande fredde',
    juices: 'Succhi',
    cocktails: 'Cocktail',
    beer: 'Birra',
    wine: 'Vino',
    spirits: 'Liquori',
    softDrinks: 'Bibite',
    other: 'Altro',
    noDrinksAvailable: 'Nessuna bevanda disponibile al momento.',
    orderSummary: 'Riepilogo ordine',
    addToOrder: "Aggiungi all'ordine",
    total: 'Totale',
    invoiceItems: 'Articoli',
  },
  pt: {
    welcome: 'Bem-vindo',
    selectLanguage: 'Selecione seu idioma',
    roomService: 'Serviço de quarto',
    drinks: 'Bebidas',
    customRequest: 'Pedido personalizado',
    invoice: 'Minha fatura',
    towels: 'Toalhas',
    helpOpeningRoom: 'Ajuda para abrir o quarto',
    cleaning: 'Limpeza',
    bathroomService: 'Serviço de banheiro',
    doNotDisturb: 'Não perturbe',
    sendRequest: 'Enviar pedido',
    requestSent: 'Pedido enviado!',
    requestSentDesc: 'Nossa equipe foi notificada e irá ajudá-lo em breve.',
    writeYourRequest: 'Escreva seu pedido aqui...',
    back: 'Voltar',
    sending: 'Enviando...',
    room: 'Quarto',
    thankYou: 'Obrigado!',
    feedback: 'Avaliação',
    overallRating: 'Experiência geral',
    serviceRating: 'Qualidade do serviço',
    cleanlinessRating: 'Limpeza',
    foodRating: 'Comida e bebidas',
    feedbackComment: 'Comentários adicionais',
    feedbackPlaceholder: 'Conte-nos sobre sua experiência...',
    submitFeedback: 'Enviar avaliação',
    ratingRequired: 'Avalie sua experiência geral',
    feedbackSent: 'Avaliação enviada!',
    feedbackSentDesc: 'Obrigado pelo seu feedback!',
    hotDrinks: 'Bebidas quentes',
    coldDrinks: 'Bebidas frias',
    juices: 'Sucos',
    cocktails: 'Coquetéis',
    beer: 'Cerveja',
    wine: 'Vinho',
    spirits: 'Destilados',
    softDrinks: 'Refrigerantes',
    other: 'Outro',
    noDrinksAvailable: 'Nenhuma bebida disponível no momento.',
    orderSummary: 'Resumo do pedido',
    addToOrder: 'Adicionar ao pedido',
    total: 'Total',
    invoiceItems: 'Itens',
  },
  ru: {
    welcome: 'Добро пожаловать',
    selectLanguage: 'Выберите язык',
    roomService: 'Обслуживание номера',
    drinks: 'Напитки',
    customRequest: 'Особый запрос',
    invoice: 'Мой счёт',
    towels: 'Полотенца',
    helpOpeningRoom: 'Помощь с открытием номера',
    cleaning: 'Уборка',
    bathroomService: 'Обслуживание ванной',
    doNotDisturb: 'Не беспокоить',
    sendRequest: 'Отправить запрос',
    requestSent: 'Запрос отправлен!',
    requestSentDesc: 'Наша команда уведомлена и поможет вам в ближайшее время.',
    writeYourRequest: 'Напишите ваш запрос здесь...',
    back: 'Назад',
    sending: 'Отправка...',
    room: 'Номер',
    thankYou: 'Спасибо!',
    feedback: 'Отзыв',
    overallRating: 'Общее впечатление',
    serviceRating: 'Качество обслуживания',
    cleanlinessRating: 'Чистота',
    foodRating: 'Еда и напитки',
    feedbackComment: 'Дополнительные комментарии',
    feedbackPlaceholder: 'Расскажите о вашем опыте...',
    submitFeedback: 'Отправить отзыв',
    ratingRequired: 'Оцените ваше общее впечатление',
    feedbackSent: 'Отзыв отправлен!',
    feedbackSentDesc: 'Спасибо за ваш отзыв!',
    hotDrinks: 'Горячие напитки',
    coldDrinks: 'Холодные напитки',
    juices: 'Соки',
    cocktails: 'Коктейли',
    beer: 'Пиво',
    wine: 'Вино',
    spirits: 'Крепкие напитки',
    softDrinks: 'Безалкогольные напитки',
    other: 'Другое',
    noDrinksAvailable: 'Напитки временно недоступны.',
    orderSummary: 'Итог заказа',
    addToOrder: 'Добавить в заказ',
    total: 'Итого',
    invoiceItems: 'Позиции',
  },
  zh: {
    welcome: '欢迎',
    selectLanguage: '请选择您的语言',
    roomService: '客房服务',
    drinks: '饮品',
    customRequest: '自定义请求',
    invoice: '我的账单',
    towels: '毛巾',
    helpOpeningRoom: '协助开门',
    cleaning: '清洁',
    bathroomService: '浴室服务',
    doNotDisturb: '请勿打扰',
    sendRequest: '发送请求',
    requestSent: '请求已发送！',
    requestSentDesc: '我们的团队已收到通知，将尽快为您服务。',
    writeYourRequest: '请在此输入您的请求...',
    back: '返回',
    sending: '发送中...',
    room: '房间',
    thankYou: '谢谢！',
    feedback: '反馈',
    overallRating: '整体体验',
    serviceRating: '服务质量',
    cleanlinessRating: '清洁度',
    foodRating: '餐饮',
    feedbackComment: '补充意见',
    feedbackPlaceholder: '请告诉我们您的体验...',
    submitFeedback: '提交反馈',
    ratingRequired: '请评价您的整体体验',
    feedbackSent: '反馈已提交！',
    feedbackSentDesc: '感谢您的反馈！',
    hotDrinks: '热饮',
    coldDrinks: '冷饮',
    juices: '果汁',
    cocktails: '鸡尾酒',
    beer: '啤酒',
    wine: '葡萄酒',
    spirits: '烈酒',
    softDrinks: '软饮料',
    other: '其他',
    noDrinksAvailable: '暂无可用饮品。',
    orderSummary: '订单摘要',
    addToOrder: '加入订单',
    total: '合计',
    invoiceItems: '项目',
  },
  ja: {
    welcome: 'ようこそ',
    selectLanguage: '言語を選択してください',
    roomService: 'ルームサービス',
    drinks: 'ドリンク',
    customRequest: 'カスタムリクエスト',
    invoice: '請求書',
    towels: 'タオル',
    helpOpeningRoom: '部屋の開錠サポート',
    cleaning: '清掃',
    bathroomService: 'バスルームサービス',
    doNotDisturb: '起こさないでください',
    sendRequest: 'リクエストを送信',
    requestSent: 'リクエスト送信完了！',
    requestSentDesc: 'スタッフに通知されました。まもなく対応いたします。',
    writeYourRequest: 'リクエストをご記入ください...',
    back: '戻る',
    sending: '送信中...',
    room: '部屋',
    thankYou: 'ありがとうございます！',
    feedback: 'フィードバック',
    overallRating: '総合評価',
    serviceRating: 'サービス品質',
    cleanlinessRating: '清潔さ',
    foodRating: '料理・ドリンク',
    feedbackComment: '追加コメント',
    feedbackPlaceholder: 'ご体験をお聞かせください...',
    submitFeedback: 'フィードバックを送信',
    ratingRequired: '総合評価をお願いします',
    feedbackSent: 'フィードバック送信完了！',
    feedbackSentDesc: 'ご意見ありがとうございます！',
    hotDrinks: 'ホットドリンク',
    coldDrinks: 'コールドドリンク',
    juices: 'ジュース',
    cocktails: 'カクテル',
    beer: 'ビール',
    wine: 'ワイン',
    spirits: 'スピリッツ',
    softDrinks: 'ソフトドリンク',
    other: 'その他',
    noDrinksAvailable: '現在ドリンクはご用意できません。',
    orderSummary: '注文内容',
    addToOrder: '注文に追加',
    total: '合計',
    invoiceItems: '項目',
  },
  ko: {
    welcome: '환영합니다',
    selectLanguage: '언어를 선택하세요',
    roomService: '룸서비스',
    drinks: '음료',
    customRequest: '맞춤 요청',
    invoice: '청구서',
    towels: '수건',
    helpOpeningRoom: '객실 열기 도움',
    cleaning: '청소',
    bathroomService: '욕실 서비스',
    doNotDisturb: '방해 금지',
    sendRequest: '요청 보내기',
    requestSent: '요청이 전송되었습니다!',
    requestSentDesc: '팀에 알림이 전달되었으며 곧 도와드리겠습니다.',
    writeYourRequest: '요청 사항을 입력하세요...',
    back: '뒤로',
    sending: '전송 중...',
    room: '객실',
    thankYou: '감사합니다!',
    feedback: '피드백',
    overallRating: '전체 경험',
    serviceRating: '서비스 품질',
    cleanlinessRating: '청결도',
    foodRating: '음식 및 음료',
    feedbackComment: '추가 의견',
    feedbackPlaceholder: '경험을 알려주세요...',
    submitFeedback: '피드백 제출',
    ratingRequired: '전체 경험을 평가해 주세요',
    feedbackSent: '피드백이 제출되었습니다!',
    feedbackSentDesc: '피드백 감사합니다!',
    hotDrinks: '따뜻한 음료',
    coldDrinks: '차가운 음료',
    juices: '주스',
    cocktails: '칵테일',
    beer: '맥주',
    wine: '와인',
    spirits: '증류주',
    softDrinks: '탄산음료',
    other: '기타',
    noDrinksAvailable: '현재 음료가 없습니다.',
    orderSummary: '주문 요약',
    addToOrder: '주문에 추가',
    total: '합계',
    invoiceItems: '항목',
  },
  tr: {
    welcome: 'Hoş geldiniz',
    selectLanguage: 'Dilinizi seçin',
    roomService: 'Oda servisi',
    drinks: 'İçecekler',
    customRequest: 'Özel istek',
    invoice: 'Faturam',
    towels: 'Havlular',
    helpOpeningRoom: 'Oda açma yardımı',
    cleaning: 'Temizlik',
    bathroomService: 'Banyo hizmeti',
    doNotDisturb: 'Rahatsız etmeyin',
    sendRequest: 'İstek gönder',
    requestSent: 'İstek gönderildi!',
    requestSentDesc: 'Ekibimiz bilgilendirildi ve size kısa sürede yardımcı olacaktır.',
    writeYourRequest: 'İsteğinizi buraya yazın...',
    back: 'Geri',
    sending: 'Gönderiliyor...',
    room: 'Oda',
    thankYou: 'Teşekkürler!',
    feedback: 'Değerlendirme',
    overallRating: 'Genel deneyim',
    serviceRating: 'Hizmet kalitesi',
    cleanlinessRating: 'Temizlik',
    foodRating: 'Yiyecek ve içecek',
    feedbackComment: 'Ek yorumlar',
    feedbackPlaceholder: 'Deneyiminizi anlatın...',
    submitFeedback: 'Değerlendirmeyi gönder',
    ratingRequired: 'Genel deneyiminizi değerlendirin',
    feedbackSent: 'Değerlendirme gönderildi!',
    feedbackSentDesc: 'Geri bildiriminiz için teşekkürler!',
    hotDrinks: 'Sıcak içecekler',
    coldDrinks: 'Soğuk içecekler',
    juices: 'Meyve suları',
    cocktails: 'Kokteyller',
    beer: 'Bira',
    wine: 'Şarap',
    spirits: 'Alkollü içecekler',
    softDrinks: 'Meşrubatlar',
    other: 'Diğer',
    noDrinksAvailable: 'Şu anda mevcut içecek yok.',
    orderSummary: 'Sipariş özeti',
    addToOrder: 'Siparişe ekle',
    total: 'Toplam',
    invoiceItems: 'Kalemler',
  },
  hi: {
    welcome: 'स्वागत है',
    selectLanguage: 'अपनी भाषा चुनें',
    roomService: 'रूम सर्विस',
    drinks: 'पेय पदार्थ',
    customRequest: 'विशेष अनुरोध',
    invoice: 'मेरा बिल',
    towels: 'तौलिये',
    helpOpeningRoom: 'कमरा खोलने में मदद',
    cleaning: 'सफ़ाई',
    bathroomService: 'बाथरूम सेवा',
    doNotDisturb: 'परेशान न करें',
    sendRequest: 'अनुरोध भेजें',
    requestSent: 'अनुरोध भेजा गया!',
    requestSentDesc: 'हमारी टीम को सूचित कर दिया गया है और वे जल्द ही आपकी सहायता करेंगे।',
    writeYourRequest: 'अपना अनुरोध यहाँ लिखें...',
    back: 'वापस',
    sending: 'भेजा जा रहा है...',
    room: 'कमरा',
    thankYou: 'धन्यवाद!',
    feedback: 'प्रतिक्रिया',
    overallRating: 'समग्र अनुभव',
    serviceRating: 'सेवा गुणवत्ता',
    cleanlinessRating: 'स्वच्छता',
    foodRating: 'खाना और पेय',
    feedbackComment: 'अतिरिक्त टिप्पणियाँ',
    feedbackPlaceholder: 'अपने अनुभव के बारे में बताएं...',
    submitFeedback: 'प्रतिक्रिया भेजें',
    ratingRequired: 'कृपया अपने समग्र अनुभव का मूल्यांकन करें',
    feedbackSent: 'प्रतिक्रिया भेजी गई!',
    feedbackSentDesc: 'आपकी प्रतिक्रिया के लिए धन्यवाद!',
    hotDrinks: 'गर्म पेय',
    coldDrinks: 'ठंडे पेय',
    juices: 'जूस',
    cocktails: 'कॉकटेल',
    beer: 'बीयर',
    wine: 'वाइन',
    spirits: 'स्पिरिट्स',
    softDrinks: 'शीतल पेय',
    other: 'अन्य',
    noDrinksAvailable: 'फ़िलहाल कोई पेय उपलब्ध नहीं है।',
    orderSummary: 'ऑर्डर सारांश',
    addToOrder: 'ऑर्डर में जोड़ें',
    total: 'कुल',
    invoiceItems: 'आइटम',
  },
  nl: {
    welcome: 'Welkom',
    selectLanguage: 'Selecteer uw taal',
    roomService: 'Roomservice',
    drinks: 'Dranken',
    customRequest: 'Speciaal verzoek',
    invoice: 'Mijn factuur',
    towels: 'Handdoeken',
    helpOpeningRoom: 'Hulp bij het openen van de kamer',
    cleaning: 'Schoonmaak',
    bathroomService: 'Badkamerservice',
    doNotDisturb: 'Niet storen',
    sendRequest: 'Verzoek verzenden',
    requestSent: 'Verzoek verzonden!',
    requestSentDesc: 'Ons team is op de hoogte gebracht en zal u spoedig helpen.',
    writeYourRequest: 'Schrijf uw verzoek hier...',
    back: 'Terug',
    sending: 'Verzenden...',
    room: 'Kamer',
    thankYou: 'Dank u!',
    feedback: 'Beoordeling',
    overallRating: 'Algehele ervaring',
    serviceRating: 'Servicekwaliteit',
    cleanlinessRating: 'Netheid',
    foodRating: 'Eten en drinken',
    feedbackComment: 'Aanvullende opmerkingen',
    feedbackPlaceholder: 'Vertel ons over uw ervaring...',
    submitFeedback: 'Beoordeling indienen',
    ratingRequired: 'Beoordeel uw algehele ervaring',
    feedbackSent: 'Beoordeling ingediend!',
    feedbackSentDesc: 'Bedankt voor uw feedback!',
    hotDrinks: 'Warme dranken',
    coldDrinks: 'Koude dranken',
    juices: 'Sappen',
    cocktails: 'Cocktails',
    beer: 'Bier',
    wine: 'Wijn',
    spirits: 'Sterke drank',
    softDrinks: 'Frisdranken',
    other: 'Overig',
    noDrinksAvailable: 'Momenteel geen dranken beschikbaar.',
    orderSummary: 'Besteloverzicht',
    addToOrder: 'Toevoegen aan bestelling',
    total: 'Totaal',
    invoiceItems: 'Artikelen',
  },
  th: {
    welcome: 'ยินดีต้อนรับ',
    selectLanguage: 'เลือกภาษาของคุณ',
    roomService: 'บริการห้องพัก',
    drinks: 'เครื่องดื่ม',
    customRequest: 'คำขอพิเศษ',
    invoice: 'ใบแจ้งหนี้',
    towels: 'ผ้าขนหนู',
    helpOpeningRoom: 'ช่วยเปิดห้อง',
    cleaning: 'ทำความสะอาด',
    bathroomService: 'บริการห้องน้ำ',
    doNotDisturb: 'ห้ามรบกวน',
    sendRequest: 'ส่งคำขอ',
    requestSent: 'ส่งคำขอแล้ว!',
    requestSentDesc: 'ทีมงานได้รับแจ้งแล้วและจะช่วยเหลือคุณในไม่ช้า',
    writeYourRequest: 'เขียนคำขอของคุณที่นี่...',
    back: 'กลับ',
    sending: 'กำลังส่ง...',
    room: 'ห้อง',
    thankYou: 'ขอบคุณ!',
    feedback: 'ความคิดเห็น',
    overallRating: 'ประสบการณ์โดยรวม',
    serviceRating: 'คุณภาพบริการ',
    cleanlinessRating: 'ความสะอาด',
    foodRating: 'อาหารและเครื่องดื่ม',
    feedbackComment: 'ความเห็นเพิ่มเติม',
    feedbackPlaceholder: 'เล่าประสบการณ์ของคุณ...',
    submitFeedback: 'ส่งความคิดเห็น',
    ratingRequired: 'กรุณาให้คะแนนประสบการณ์โดยรวม',
    feedbackSent: 'ส่งความคิดเห็นแล้ว!',
    feedbackSentDesc: 'ขอบคุณสำหรับความคิดเห็นของคุณ!',
    hotDrinks: 'เครื่องดื่มร้อน',
    coldDrinks: 'เครื่องดื่มเย็น',
    juices: 'น้ำผลไม้',
    cocktails: 'ค็อกเทล',
    beer: 'เบียร์',
    wine: 'ไวน์',
    spirits: 'สุรา',
    softDrinks: 'น้ำอัดลม',
    other: 'อื่นๆ',
    noDrinksAvailable: 'ขณะนี้ไม่มีเครื่องดื่ม',
    orderSummary: 'สรุปคำสั่งซื้อ',
    addToOrder: 'เพิ่มในคำสั่งซื้อ',
    total: 'รวม',
    invoiceItems: 'รายการ',
  },
  el: {
    welcome: 'Καλώς ήρθατε',
    selectLanguage: 'Επιλέξτε γλώσσα',
    roomService: 'Υπηρεσία δωματίου',
    drinks: 'Ποτά',
    customRequest: 'Ειδικό αίτημα',
    invoice: 'Τιμολόγιό μου',
    towels: 'Πετσέτες',
    helpOpeningRoom: 'Βοήθεια με το δωμάτιο',
    cleaning: 'Καθαρισμός',
    bathroomService: 'Υπηρεσία μπάνιου',
    doNotDisturb: 'Μην ενοχλείτε',
    sendRequest: 'Αποστολή αιτήματος',
    requestSent: 'Αίτημα εστάλη!',
    requestSentDesc: 'Η ομάδα μας ενημερώθηκε και θα σας εξυπηρετήσει σύντομα.',
    writeYourRequest: 'Γράψτε το αίτημά σας εδώ...',
    back: 'Πίσω',
    sending: 'Αποστολή...',
    room: 'Δωμάτιο',
    thankYou: 'Ευχαριστούμε!',
    feedback: 'Αξιολόγηση',
    overallRating: 'Συνολική εμπειρία',
    serviceRating: 'Ποιότητα εξυπηρέτησης',
    cleanlinessRating: 'Καθαριότητα',
    foodRating: 'Φαγητό και ποτά',
    feedbackComment: 'Πρόσθετα σχόλια',
    feedbackPlaceholder: 'Πείτε μας για την εμπειρία σας...',
    submitFeedback: 'Υποβολή αξιολόγησης',
    ratingRequired: 'Αξιολογήστε τη συνολική εμπειρία σας',
    feedbackSent: 'Αξιολόγηση υποβλήθηκε!',
    feedbackSentDesc: 'Ευχαριστούμε για την αξιολόγησή σας!',
    hotDrinks: 'Ζεστά ροφήματα',
    coldDrinks: 'Κρύα ποτά',
    juices: 'Χυμοί',
    cocktails: 'Κοκτέιλ',
    beer: 'Μπύρα',
    wine: 'Κρασί',
    spirits: 'Αλκοολούχα',
    softDrinks: 'Αναψυκτικά',
    other: 'Άλλο',
    noDrinksAvailable: 'Δεν υπάρχουν διαθέσιμα ποτά αυτή τη στιγμή.',
    orderSummary: 'Σύνοψη παραγγελίας',
    addToOrder: 'Προσθήκη στην παραγγελία',
    total: 'Σύνολο',
    invoiceItems: 'Είδη',
  },
  pl: {
    welcome: 'Witamy',
    selectLanguage: 'Wybierz język',
    roomService: 'Obsługa pokoju',
    drinks: 'Napoje',
    customRequest: 'Specjalne życzenie',
    invoice: 'Mój rachunek',
    towels: 'Ręczniki',
    helpOpeningRoom: 'Pomoc z otwarciem pokoju',
    cleaning: 'Sprzątanie',
    bathroomService: 'Obsługa łazienki',
    doNotDisturb: 'Nie przeszkadzać',
    sendRequest: 'Wyślij prośbę',
    requestSent: 'Prośba wysłana!',
    requestSentDesc: 'Nasz zespół został powiadomiony i wkrótce Ci pomoże.',
    writeYourRequest: 'Napisz swoją prośbę tutaj...',
    back: 'Wstecz',
    sending: 'Wysyłanie...',
    room: 'Pokój',
    thankYou: 'Dziękujemy!',
    feedback: 'Opinia',
    overallRating: 'Ogólne wrażenie',
    serviceRating: 'Jakość obsługi',
    cleanlinessRating: 'Czystość',
    foodRating: 'Jedzenie i napoje',
    feedbackComment: 'Dodatkowe uwagi',
    feedbackPlaceholder: 'Opowiedz o swoim doświadczeniu...',
    submitFeedback: 'Wyślij opinię',
    ratingRequired: 'Oceń swoje ogólne wrażenie',
    feedbackSent: 'Opinia wysłana!',
    feedbackSentDesc: 'Dziękujemy za opinię!',
    hotDrinks: 'Napoje gorące',
    coldDrinks: 'Napoje zimne',
    juices: 'Soki',
    cocktails: 'Koktajle',
    beer: 'Piwo',
    wine: 'Wino',
    spirits: 'Alkohole mocne',
    softDrinks: 'Napoje gazowane',
    other: 'Inne',
    noDrinksAvailable: 'Brak dostępnych napojów.',
    orderSummary: 'Podsumowanie zamówienia',
    addToOrder: 'Dodaj do zamówienia',
    total: 'Razem',
    invoiceItems: 'Pozycje',
  },
};

export function t(lang: string, key: string): string {
  return UI_TRANSLATIONS[lang]?.[key] || UI_TRANSLATIONS['en']?.[key] || key;
}
